version: '3.8'
services:
  app-ui:
    container_name: rt-5gms-application-provider
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/ui
      - ./static:/ui/static
    restart: unless-stopped
