type: environment.insomnia.rest/5.0
schema_version: "5.1"
name: 5GMS Application Function Environment Imported
meta:
  id: wrk_78dd409b197145a0ab5532e6317a34c7
  created: 1774514989876
  modified: 1774514989876
  description: ""
environments:
  name: 5G-MAG
  meta:
    id: env_e4e5fa33d20d461584edf1f7f94aa568
    created: 1771856165563
    modified: 1774619402712
    isPrivate: false
  data:
    provisioning_session_id: 6477d92a-03a4-41ef-9b80-db09e44c2897
    m1_url: http://localhost:5555
    m5_url: http://localhost:7778
    maf_url: http://localhost:6464
    ue_ip: 10.45.0.5
    policy_template_id: ""
    dynamic_policy_id: ""
    update_policy_template_url: ""
    na_session_id: ""
    metrics_reporting_configuration_id: ""
