name: Docker Compose

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compose:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Docker Compose
      run: |
        docker-compose build
        docker-compose up -d
        docker-compose down
