name: Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-attempts: 3

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker-compose build

    - name: Run Integration Tests
      run: |
        docker-compose up -d
        docker-compose exec rt-5gms-m1-management-ui sh -c "cd tests && pytest integration_test.py"
        docker-compose down
