name: Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker-compose build

    - name: Run Integration Tests
      run: |
        docker-compose up -d
        docker-compose exec app-ui sh -c "cd tests && pytest integration_test.py"
        docker-compose down
